/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import biblioteca.Biblioteca;
import biblioteca.Libro;
import biblioteca.Revista;
import biblioteca.Tesis;
import javax.swing.JOptionPane;

/**
 *
 * @author Lusvin
 */
public class CargaMasiva extends javax.swing.JFrame {

    /**
     * Creates new form CargaMasiva
     */
    public CargaMasiva() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtback = new javax.swing.JButton();
        jbtncarga = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxareaDatos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Pegue el texto de carga masiva...");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 270, 30));

        jbtback.setText("Regresar");
        jbtback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtbackMouseClicked(evt);
            }
        });
        jPanel1.add(jbtback, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 120, 40));

        jbtncarga.setText("Cargar Datos");
        jbtncarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtncargaMouseClicked(evt);
            }
        });
        jPanel1.add(jbtncarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 140, 50));

        jtxareaDatos.setColumns(20);
        jtxareaDatos.setRows(5);
        jScrollPane1.setViewportView(jtxareaDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 640, 300));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/img/gradientgranmedia.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtbackMouseClicked
        this.setVisible(false);
//        Admin ad = new Admin();
//        ad.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtbackMouseClicked

    private void jbtncargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtncargaMouseClicked
        //Separando las filas    
        String filas[] = jtxareaDatos.getText().split("\n");
        int columnas = filas[0].split(";").length;
        //String datos[] = filas[columnas].split(";");

        for (int i = 0; i < filas.length; i++) {

            String datos[] = filas[i].split(";");

            for (int j = 0; j < 1; j++) {
                if (Integer.parseInt(datos[0]) == 0) {
                    System.out.println("Esto es un libro");
                    String palabra[] = datos[6].split(",");
                    String tema[] = datos[8].split(",");
                    biblioteca.Biblioteca.libros[biblioteca.Biblioteca.contlibros] = new Libro(Integer.parseInt(datos[9]), Integer.parseInt(datos[13]), Integer.parseInt(datos[3]), 0, Integer.parseInt(datos[2]), datos[1], datos[7], Integer.parseInt(datos[5]), palabra, tema, datos[4]);
                    biblioteca.Biblioteca.contlibros++;
                    
                } else if (Integer.parseInt(datos[0]) == 1) {
                    System.out.println("Esto es una revista");
                    String palabra[] = datos[6].split(",");
                    String tema[] = datos[8].split(",");
                    biblioteca.Biblioteca.revistas[biblioteca.Biblioteca.contrevistas] = new Revista(/*Integer.parseInt(datos[3])*/Biblioteca.contrevistas, datos[10], Integer.parseInt(datos[9]), Integer.parseInt(datos[13]), Integer.parseInt(datos[11]), 1, Integer.parseInt(datos[2]), datos[1], datos[7], Integer.parseInt(datos[5]), palabra, tema, datos[4]);
                    biblioteca.Biblioteca.contrevistas++;

                } else if (Integer.parseInt(datos[0]) == 2) {
                    System.out.println("Esto en una tesis");
                    String palabra[] = datos[6].split(",");
                String tema[] = datos[8].split(",");
                biblioteca.Biblioteca.tesis[biblioteca.Biblioteca.conttesis] = new Tesis(/*Integer.parseInt(datos[3])*/Biblioteca.conttesis,  Integer.parseInt(datos[9]), Integer.parseInt(datos[13]),datos[12], 2, Integer.parseInt(datos[2]), datos[1], datos[7], Integer.parseInt(datos[5]), palabra, tema, datos[4]);
                biblioteca.Biblioteca.conttesis++;
                }

            }
            System.out.println();
        }
         JOptionPane.showMessageDialog(null, "Se cargaron: \t \n"+ "\t\t " + biblioteca.Biblioteca.contlibros + " Libros " +"\n" + "\t\t "+biblioteca.Biblioteca.contrevistas+ " Revistas " +"\n" + "\t\t "+biblioteca.Biblioteca.conttesis+ "  Tesis " , "Documentos agregados correctamente...", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtncargaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargaMasiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargaMasiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargaMasiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargaMasiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargaMasiva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtback;
    private javax.swing.JButton jbtncarga;
    private javax.swing.JTextArea jtxareaDatos;
    // End of variables declaration//GEN-END:variables
}
