/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import biblioteca.*;

import javax.swing.JOptionPane;

/**
 *
 * @author Lusvin
 */
public class CrearBiblio extends javax.swing.JFrame {

    /**
     * Creates new form CrearBiblio
     */
    public CrearBiblio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbcopi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtejemplares = new javax.swing.JTextField();
        txtautor = new javax.swing.JTextField();
        txtaño = new javax.swing.JTextField();
        txttitulo = new javax.swing.JTextField();
        txtdescrip = new javax.swing.JTextField();
        txtpalabra = new javax.swing.JTextField();
        txtedicion = new javax.swing.JTextField();
        txttemas = new javax.swing.JTextField();
        txtarea = new javax.swing.JTextField();
        txtcategoria = new javax.swing.JTextField();
        txtisbn = new javax.swing.JTextField();
        txttamanio = new javax.swing.JTextField();
        txtcopias = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btncargamasiva = new javax.swing.JButton();
        jcboxdoc = new javax.swing.JComboBox<>();
        btncancelar = new javax.swing.JButton();
        btncargar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtdisponible = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbcopi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbcopi.setText("COPIAS:");
        jPanel1.add(lbcopi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 60, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("EDICIÓN:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 100, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("TIPO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("AUTOR:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("AÑO:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("TITULO:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("DESCRIPCION:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 100, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("TEMAS:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("CATEGORIA:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("AREA:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("PALABRAS:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 100, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("EJEMPLARES:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 90, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("DISPO:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 50, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("ISBN-ID:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 20));

        txtejemplares.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtejemplares, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 70, -1));

        txtautor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, -1));

        txtaño.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, -1));

        txttitulo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txttitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 200, -1));

        txtdescrip.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtdescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 200, -1));

        txtpalabra.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtpalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 200, -1));

        txtedicion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtedicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 200, -1));

        txttemas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txttemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 200, -1));

        txtarea.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 200, -1));

        txtcategoria.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 200, -1));

        txtisbn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 200, -1));

        txttamanio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txttamanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 60, -1));

        txtcopias.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtcopias, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 70, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Carga Individual");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 30));

        btncargamasiva.setText("Carga Masiva");
        btncargamasiva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncargamasivaMouseClicked(evt);
            }
        });
        jPanel1.add(btncargamasiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 140, 30));

        jcboxdoc.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jcboxdoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Libro", "Revista", "Tesis", "Libro Digital" }));
        jcboxdoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxdocActionPerformed(evt);
            }
        });
        jPanel1.add(jcboxdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 90, -1));

        btncancelar.setText("Cancelar");
        btncancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 100, 30));

        btncargar.setText("Cargar");
        btncargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncargarMouseClicked(evt);
            }
        });
        jPanel1.add(btncargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 100, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("TAMAÑO:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 70, 20));

        txtdisponible.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtdisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 60, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/img/gradientmediun.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelarMouseClicked
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarMouseClicked

    private void jcboxdocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxdocActionPerformed

        if (((String) jcboxdoc.getSelectedItem()).equalsIgnoreCase("-")) {
            txtarea.setEnabled(false);
            txtautor.setEnabled(false);
            txtaño.setEnabled(false);
            txtcategoria.setEnabled(false);
            txtcopias.setEnabled(false);
            txtdescrip.setEnabled(false);
            txtedicion.setEnabled(false);
            txtejemplares.setEnabled(false);
            txtisbn.setEnabled(false);
            txtpalabra.setEnabled(false);
            txttamanio.setEnabled(false);
            txttemas.setEnabled(false);
            txttitulo.setEnabled(false);
            txtdisponible.setEnabled(false);
        } else if (((String) jcboxdoc.getSelectedItem()).equalsIgnoreCase("Libro")) {
            txtcategoria.setEnabled(false);
            txtejemplares.setEnabled(false);
            txtarea.setEnabled(false);
            txttamanio.setEnabled(false);

            txtautor.setEnabled(true);
            txtaño.setEnabled(true);
            txtcopias.setEnabled(true);
            txtdescrip.setEnabled(true);
            txtedicion.setEnabled(true);
            txtisbn.setEnabled(true);
            txtpalabra.setEnabled(true);
            txttemas.setEnabled(true);
            txttitulo.setEnabled(true);
            txtdisponible.setEnabled(true);
        } else if (((String) jcboxdoc.getSelectedItem()).equalsIgnoreCase("Revista")) {
            txtarea.setEnabled(false);
            txttamanio.setEnabled(false);

            txtautor.setEnabled(true);
            txtaño.setEnabled(true);
            txtcategoria.setEnabled(true);
            txtcopias.setEnabled(true);
            txtdescrip.setEnabled(true);
            txtedicion.setEnabled(true);
            txtejemplares.setEnabled(true);
            txtisbn.setEnabled(true);
            txtpalabra.setEnabled(true);
            txttemas.setEnabled(true);
            txttitulo.setEnabled(true);
            txtdisponible.setEnabled(true);
        } else if (((String) jcboxdoc.getSelectedItem()).equalsIgnoreCase("Tesis")) {
            txtcategoria.setEnabled(false);
            txtejemplares.setEnabled(false);
            txttamanio.setEnabled(false);

            txtarea.setEnabled(true);
            txtautor.setEnabled(true);
            txtaño.setEnabled(true);
            txtcopias.setEnabled(true);
            txtdescrip.setEnabled(true);
            txtedicion.setEnabled(true);
            txtisbn.setEnabled(true);
            txtpalabra.setEnabled(true);
            txttemas.setEnabled(true);
            txttitulo.setEnabled(true);
            txtdisponible.setEnabled(true);
        } else if (((String) jcboxdoc.getSelectedItem()).equalsIgnoreCase("Libro digital")) {
            txtarea.setEnabled(false);
            txtautor.setEnabled(true);
            txtaño.setEnabled(true);
            txtcategoria.setEnabled(false);
            txtcopias.setEnabled(false);
            txtdescrip.setEnabled(true);
            txtedicion.setEnabled(true);
            txtejemplares.setEnabled(false);
            txtisbn.setEnabled(true);
            txtpalabra.setEnabled(true);
            txttamanio.setEnabled(true);
            txttemas.setEnabled(true);
            txttitulo.setEnabled(true);
            txtdisponible.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboxdocActionPerformed


    private void btncargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncargarMouseClicked
        boolean permite = false;

        if (txtisbn.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese Datos por favor...", "Faltan Datos ", JOptionPane.WARNING_MESSAGE);
        } else if (((String) jcboxdoc.getSelectedItem()).equalsIgnoreCase("Libro")) {
            if (biblioteca.Biblioteca.libros[0] == null) {
                permite = true;
            } else {
                for (int i = 0; i < biblioteca.Biblioteca.contlibros; i++) {
                    if (biblioteca.Biblioteca.libros[i].getIsbn() == Integer.parseInt(txtisbn.getText())) {
                        JOptionPane.showMessageDialog(null, "El Documento con este ID ya existe...", "Error al crear documento", JOptionPane.WARNING_MESSAGE);
                    } else {
                        permite = true;
                    }
                }
            }
            if (permite) {
                String palabra[] = txtpalabra.getText().split(",");
                String tema[] = txttemas.getText().split(",");
                biblioteca.Biblioteca.libros[biblioteca.Biblioteca.contlibros] = new Libro(Integer.parseInt(txtcopias.getText()), Integer.parseInt(txtdisponible.getText()), Integer.parseInt(txtisbn.getText()), 0, Integer.parseInt(txtaño.getText()), txtautor.getText(), txtdescrip.getText(), Integer.parseInt(txtedicion.getText()), palabra, tema, txttitulo.getText());
                JOptionPane.showMessageDialog(null, "El Libro: " + biblioteca.Biblioteca.libros[biblioteca.Biblioteca.contlibros].getTitulo() + " fue agregado exitosamente", "Libro agregado", JOptionPane.INFORMATION_MESSAGE);
                biblioteca.Biblioteca.contlibros++;
                setVisible(false);
            }

        } else if (((String) jcboxdoc.getSelectedItem()).equalsIgnoreCase("Revista")) {
            if (biblioteca.Biblioteca.revistas[0] == null) {
                permite = true;
            } else {
                for (int i = 0; i < biblioteca.Biblioteca.contrevistas; i++) {
                    if (biblioteca.Biblioteca.revistas[i].getId()== Integer.parseInt(txtisbn.getText())) {
                        JOptionPane.showMessageDialog(null, "El Documento con este ID ya existe...", "Error al crear documento", JOptionPane.WARNING_MESSAGE);
                    } else {
                        permite = true;
                    }
                }
            }
            if (permite) {
                String palabra[] = txtpalabra.getText().split(",");
                String tema[] = txttemas.getText().split(",");
                biblioteca.Biblioteca.revistas[biblioteca.Biblioteca.contrevistas] = new Revista(Integer.parseInt(txtisbn.getText()), txtcategoria.getText(), Integer.parseInt(txtcopias.getText()), Integer.parseInt(txtdisponible.getText()), Integer.parseInt(txtejemplares.getText()) , 1, Integer.parseInt(txtaño.getText()), txtautor.getText(), txtdescrip.getText(), Integer.parseInt(txtedicion.getText()), palabra, tema, txttitulo.getText());
                JOptionPane.showMessageDialog(null, "La Revista: " + biblioteca.Biblioteca.revistas[biblioteca.Biblioteca.contrevistas].getTitulo() + " fue agregada exitosamente", "Revista agregada", JOptionPane.INFORMATION_MESSAGE);
                biblioteca.Biblioteca.contrevistas++;
                setVisible(false);
            }
            

        }else if (((String) jcboxdoc.getSelectedItem()).equalsIgnoreCase("Tesis")) {
            if (biblioteca.Biblioteca.tesis[0] == null) {
                permite = true;
            } else {
                for (int i = 0; i < biblioteca.Biblioteca.conttesis; i++) {
                    if (biblioteca.Biblioteca.tesis[i].getId()== Integer.parseInt(txtisbn.getText())) {
                        JOptionPane.showMessageDialog(null, "El Documento con este ID ya existe...", "Error al crear documento", JOptionPane.WARNING_MESSAGE);
                    } else {
                        permite = true;
                    }
                }
            }
            if (permite) {
                String palabra[] = txtpalabra.getText().split(",");
                String tema[] = txttemas.getText().split(",");
                biblioteca.Biblioteca.tesis[biblioteca.Biblioteca.conttesis] = new Tesis(Integer.parseInt(txtisbn.getText()),  Integer.parseInt(txtcopias.getText()), Integer.parseInt(txtdisponible.getText()),txtarea.getText(), 2, Integer.parseInt(txtaño.getText()), txtautor.getText(), txtdescrip.getText(), Integer.parseInt(txtedicion.getText()), palabra, tema, txttitulo.getText());
                JOptionPane.showMessageDialog(null, "La Tesis: " + biblioteca.Biblioteca.tesis[biblioteca.Biblioteca.conttesis].getTitulo() + " fue agregada exitosamente", "Tesis agregada", JOptionPane.INFORMATION_MESSAGE);
                biblioteca.Biblioteca.conttesis++;
                setVisible(false);
            }
            

        }else if (((String) jcboxdoc.getSelectedItem()).equalsIgnoreCase("Libro Digital")) {
            if (biblioteca.Biblioteca.librosDigital[0] == null) {
                permite = true;
            } else {
                for (int i = 0; i < biblioteca.Biblioteca.contlibrodigital; i++) {
                    if (biblioteca.Biblioteca.librosDigital[i].getId()== Integer.parseInt(txtisbn.getText())) {
                        JOptionPane.showMessageDialog(null, "El Documento con este ID ya existe...", "Error al crear documento", JOptionPane.WARNING_MESSAGE);
                    } else {
                        permite = true;
                    }
                }
            }
            if (permite) {
                String palabra[] = txtpalabra.getText().split(",");
                String tema[] = txttemas.getText().split(",");
                biblioteca.Biblioteca.librosDigital[biblioteca.Biblioteca.contlibrodigital] = new LibroDigital(Integer.parseInt(txtisbn.getText()),  Integer.parseInt(txttamanio.getText()), 3, Integer.parseInt(txtaño.getText()), txtautor.getText(), txtdescrip.getText(), Integer.parseInt(txtedicion.getText()), palabra, tema, txttitulo.getText());
                JOptionPane.showMessageDialog(null, "El Libro Digital: " + biblioteca.Biblioteca.librosDigital[biblioteca.Biblioteca.contlibrodigital].getTitulo() + " fue agregado exitosamente", "Libro digital agregado", JOptionPane.INFORMATION_MESSAGE);
                biblioteca.Biblioteca.contlibrodigital++;
                setVisible(false);
            }

        }

    }//GEN-LAST:event_btncargarMouseClicked

    private void btncargamasivaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncargamasivaMouseClicked
        this.setVisible(false);
               CargaMasiva cm = new CargaMasiva();
        cm.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btncargamasivaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearBiblio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearBiblio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearBiblio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearBiblio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearBiblio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncargamasiva;
    private javax.swing.JButton btncargar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcboxdoc;
    private javax.swing.JLabel lbcopi;
    private javax.swing.JTextField txtarea;
    private javax.swing.JTextField txtautor;
    private javax.swing.JTextField txtaño;
    private javax.swing.JTextField txtcategoria;
    private javax.swing.JTextField txtcopias;
    private javax.swing.JTextField txtdescrip;
    private javax.swing.JTextField txtdisponible;
    private javax.swing.JTextField txtedicion;
    private javax.swing.JTextField txtejemplares;
    private javax.swing.JTextField txtisbn;
    private javax.swing.JTextField txtpalabra;
    private javax.swing.JTextField txttamanio;
    private javax.swing.JTextField txttemas;
    private javax.swing.JTextField txttitulo;
    // End of variables declaration//GEN-END:variables
}
