/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import biblioteca.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Lusvin
 */
public class CrearUser extends javax.swing.JFrame {

    /**
     * Creates new form CrearUser
     */
    public CrearUser() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jbtcancelar = new javax.swing.JButton();
        jbtcrearuser = new javax.swing.JButton();
        jtxid = new javax.swing.JTextField();
        jtxnombre = new javax.swing.JTextField();
        jtxapellido = new javax.swing.JTextField();
        jtxuser = new javax.swing.JTextField();
        jcbrol = new javax.swing.JComboBox<>();
        jtxpassconfirm = new javax.swing.JPasswordField();
        jtxpass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Usuario");
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Confirmar Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 160, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("ID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Crear Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 140, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Apellido:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("User:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Rol:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Contraseña:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, 30));

        jbtcancelar.setText("Cancelar");
        jbtcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtcancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtcancelarMouseClicked(evt);
            }
        });
        jPanel1.add(jbtcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 90, 40));

        jbtcrearuser.setText("Crear");
        jbtcrearuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtcrearuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtcrearuserMouseClicked(evt);
            }
        });
        jbtcrearuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcrearuserActionPerformed(evt);
            }
        });
        jPanel1.add(jbtcrearuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 90, 40));
        jPanel1.add(jtxid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 150, 25));
        jPanel1.add(jtxnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 150, 25));
        jPanel1.add(jtxapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 150, 25));
        jPanel1.add(jtxuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 150, 25));

        jcbrol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Estudiante", "Catedrático" }));
        jPanel1.add(jcbrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 150, 30));
        jPanel1.add(jtxpassconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 140, 30));
        jPanel1.add(jtxpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/img/gradientmediun.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtcrearuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcrearuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtcrearuserActionPerformed

    private void jbtcancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtcancelarMouseClicked
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtcancelarMouseClicked

    private void jbtcrearuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtcrearuserMouseClicked
       
        
        //System.out.println("valor de contador "+biblioteca.Biblioteca.contuser);
        boolean permite = false;
       // System.out.println("user en posicion 1: " + biblioteca.Biblioteca.users[0]);

        if (jtxid.getText().length() == 0 || 0 == jtxuser.getText().length()) {
            JOptionPane.showMessageDialog(null, "Ingrese Datos por favor...", "Faltan Datos ", JOptionPane.WARNING_MESSAGE);
        } else if (!(new String(jtxpass.getPassword()).equals(new String(jtxpassconfirm.getPassword())))) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden...", "Error al crear usuario", JOptionPane.WARNING_MESSAGE);
        } else if (biblioteca.Biblioteca.users[0]==null) {
            permite = true;
              System.out.println(biblioteca.Biblioteca.contuser);
        } else {
            for (int i = 0; i < biblioteca.Biblioteca.contuser; i++) {
                if (biblioteca.Biblioteca.users[i].getId() == Integer.parseInt(jtxid.getText())) {
                    JOptionPane.showMessageDialog(null, "El usuario con éste ID ya existe...", "Error al crear usuario", JOptionPane.WARNING_MESSAGE);
                } else {
                    permite = true;
                }
            }
        }
        if (permite) {
                       biblioteca.Biblioteca.users[biblioteca.Biblioteca.contuser]= new Usuario(Integer.parseInt(jtxid.getText()), jtxnombre.getText(), jtxapellido.getText(), jtxuser.getText(), (String) jcbrol.getSelectedItem(), new String(jtxpass.getPassword())); 
           
//            biblioteca.Biblioteca.users[0].setId(23); //Integer.parseInt(jtxid.getText())
//            biblioteca.Biblioteca.users[0].setNombre(jtxnombre.getText());
//            biblioteca.Biblioteca.users[0].setApellido(jtxapellido.getText());
//            biblioteca.Biblioteca.users[0].setUser(jtxuser.getText());
//            biblioteca.Biblioteca.users[0].setRol((String) jcbrol.getSelectedItem());
//            biblioteca.Biblioteca.users[0].setPassword(new String(jtxpass.getPassword()));
            JOptionPane.showMessageDialog(null, "El usuario: " + biblioteca.Biblioteca.users[biblioteca.Biblioteca.contuser].getNombre() + " fue agregado exitosamente", "Usuario agregado", JOptionPane.INFORMATION_MESSAGE);
            biblioteca.Biblioteca.contuser++;
            setVisible(false);

          }
    }//GEN-LAST:event_jbtcrearuserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtcancelar;
    private javax.swing.JButton jbtcrearuser;
    private javax.swing.JComboBox<String> jcbrol;
    private javax.swing.JTextField jtxapellido;
    private javax.swing.JTextField jtxid;
    private javax.swing.JTextField jtxnombre;
    private javax.swing.JPasswordField jtxpass;
    private javax.swing.JPasswordField jtxpassconfirm;
    private javax.swing.JTextField jtxuser;
    // End of variables declaration//GEN-END:variables
}
