package Presentacion;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lusvin
 */
public class Login extends javax.swing.JFrame {

    PantallaInicio pi = new PantallaInicio();
    String userlog;
    String userlogpass;
    static int userlogpos;

    public Login() {

        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ftxtuser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        fpassuser = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jbtingresarlog = new javax.swing.JButton();
        jbtcancelarlog = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMaximumSize(new java.awt.Dimension(350, 500));
        setName("frLogin"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(350, 500));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ftxtuser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ftxtuser.setToolTipText("Ingrese nickname");
        ftxtuser.setBorder(null);
        jPanel1.add(ftxtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 210, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 250, 10));
        jPanel1.add(fpassuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 210, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 250, 10));

        jbtingresarlog.setText("Ingresar");
        jbtingresarlog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtingresarlogMouseClicked(evt);
            }
        });
        jbtingresarlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtingresarlogActionPerformed(evt);
            }
        });
        jPanel1.add(jbtingresarlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 110, 40));

        jbtcancelarlog.setText("Cancelar");
        jbtcancelarlog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtcancelarlogMouseClicked(evt);
            }
        });
        jbtcancelarlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcancelarlogActionPerformed(evt);
            }
        });
        jPanel1.add(jbtcancelarlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 110, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 110, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/img/login.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 140, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/img/gradientmediun.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtcancelarlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcancelarlogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtcancelarlogActionPerformed

    private void jbtcancelarlogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtcancelarlogMouseClicked
        pi.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_jbtcancelarlogMouseClicked


    private void jbtingresarlogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtingresarlogMouseClicked

        for (int i = 0; i < biblioteca.Biblioteca.contuser; i++) {
            if (biblioteca.Biblioteca.users[i].getUser().equalsIgnoreCase(ftxtuser.getText())) {
                this.userlog = biblioteca.Biblioteca.users[i].getUser();
                this.userlogpass = biblioteca.Biblioteca.users[i].getPassword();
                this.userlogpos = i;
            } else {
                //this.userlog = null;
            }
        }

        if (ftxtuser.getText().length() == 0 && 0 == fpassuser.getPassword().length) {
            JOptionPane.showMessageDialog(null, "Ingrese Datos por favor...", "Error de Datos ", JOptionPane.WARNING_MESSAGE);
        } else if (biblioteca.Biblioteca.admin1.getUser().equalsIgnoreCase(ftxtuser.getText()) && biblioteca.Biblioteca.admin1.getPassword().equals(new String(fpassuser.getPassword()))) {
            this.setVisible(false);
            Admin ad = new Admin();
            ad.setVisible(true);
            pi.setVisible(false);
        } else if (biblioteca.Biblioteca.admin1.getUser().equalsIgnoreCase(ftxtuser.getText()) && !biblioteca.Biblioteca.admin1.getPassword().equals(new String(fpassuser.getPassword()))) {
            JOptionPane.showMessageDialog(null, "Credencial de administrador incorrecta...", "Error de credenciales ", JOptionPane.WARNING_MESSAGE);
        } else if (userlog == null) {
            JOptionPane.showMessageDialog(null, "El usuario no existe, ponerse en contacto con el Administrador...", "Error de Usuario ", JOptionPane.WARNING_MESSAGE);
        } else if (userlog.equalsIgnoreCase(ftxtuser.getText()) && !userlogpass.equals(new String(fpassuser.getPassword()))) {
            JOptionPane.showMessageDialog(null, "El usuario y contraseña no coinciden revise sus datos...", "Error de credenciales ", JOptionPane.WARNING_MESSAGE);
        } else if (userlog.equalsIgnoreCase(ftxtuser.getText()) && userlogpass.equals(new String(fpassuser.getPassword()))) {
            this.setVisible(false);
            User us = new User();
            us.setVisible(true);
            pi.setVisible(false);
        }

        System.out.print(userlog + userlogpass + userlogpos);


    }//GEN-LAST:event_jbtingresarlogMouseClicked

    private void jbtingresarlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtingresarlogActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtingresarlogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField fpassuser;
    private javax.swing.JTextField ftxtuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtcancelarlog;
    private javax.swing.JButton jbtingresarlog;
    // End of variables declaration//GEN-END:variables
}
