/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Lusvin
 */
public class VerUser extends javax.swing.JFrame {

    /**
     * Creates new form CrearUser
     */
    public VerUser() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbtcancelar = new javax.swing.JButton();
        jtbbuscar = new javax.swing.JButton();
        jtxid = new javax.swing.JTextField();
        jtxnombre = new javax.swing.JTextField();
        jtxapellido = new javax.swing.JTextField();
        jtxuser = new javax.swing.JTextField();
        jtxrol = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar Usuario");
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("ID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Ver Usuario Individual");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 200, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Apellido:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("User:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Rol:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, 30));

        jbtcancelar.setText("Cancelar");
        jbtcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtcancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtcancelarMouseClicked(evt);
            }
        });
        jPanel1.add(jbtcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 90, 40));

        jtbbuscar.setText("Buscar");
        jtbbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtbbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbbuscarMouseClicked(evt);
            }
        });
        jPanel1.add(jtbbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 100, 50));
        jPanel1.add(jtxid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 150, 25));

        jtxnombre.setEnabled(false);
        jPanel1.add(jtxnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 150, 25));

        jtxapellido.setEnabled(false);
        jPanel1.add(jtxapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 150, 25));

        jtxuser.setEnabled(false);
        jPanel1.add(jtxuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 150, 25));

        jtxrol.setEnabled(false);
        jPanel1.add(jtxrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 150, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/img/gradientmediun.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtcancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtcancelarMouseClicked
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtcancelarMouseClicked

    private void jtbbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbbuscarMouseClicked

        boolean encontrar = false;
        if (jtxid.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese ID valido...", "Faltan Datos ", JOptionPane.WARNING_MESSAGE);
        } else {
            for (int i = 0; i < biblioteca.Biblioteca.contuser; i++) {
                if (biblioteca.Biblioteca.users[i].getId().equals(Integer.parseInt(jtxid.getText()))) {
                    jtxnombre.setText(biblioteca.Biblioteca.users[i].getNombre());
                    jtxapellido.setText(biblioteca.Biblioteca.users[i].getApellido());
                    jtxuser.setText(biblioteca.Biblioteca.users[i].getUser());
                    jtxrol.setText(biblioteca.Biblioteca.users[i].getRol());
                    encontrar = true;
                }

            }
            if (!encontrar) {
               JOptionPane.showMessageDialog(null, "El ID no esta registrado", "Sin Registro ", JOptionPane.WARNING_MESSAGE); 
            }
            

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jtbbuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtcancelar;
    private javax.swing.JButton jtbbuscar;
    private javax.swing.JTextField jtxapellido;
    private javax.swing.JTextField jtxid;
    private javax.swing.JTextField jtxnombre;
    private javax.swing.JTextField jtxrol;
    private javax.swing.JTextField jtxuser;
    // End of variables declaration//GEN-END:variables
}
